### ISSUE TITLE
Can't build 1.1.0 with JitPack

### ISSUE THREAD

**Issue by Cir0X** [Hopding/JRPiCam#10]
I prefer to add my dependencies not directly as a jar, instead letting my build tool do the work for me

[JitPack Log](https://jitpack.io/com/github/Hopding/JRPiCam/v1.1.0/build.log)

**Comment by Hopding** [comment]
Hi @Cir0x. Thanks for taking the time to report this issue! I'll try to look into it this weekend :+1: (afraid I won't have time until then).

**Comment by Hopding** [comment]
@Cir0X Fixed. Please use [v1.1.1](https://jitpack.io/#Hopding/JRPiCam/v1.1.1) :+1:

**Comment by Cir0X** [comment]
Thanks.
Keep up the good work!
