### ISSUE TITLE
Java version to be used?

### ISSUE THREAD

**Issue by Juxgit** [Hopding/JRPiCam#12]
Hi, 

This is not be issue in JRPiCam, but generally. I'm using Raspberry PI v3 /Rasbian with Eclipse IDE and I'm getting (trying to do basic tutorial (from: https://github.com/Hopding/JRPiCam)):
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/hopding/jrpicam/RPiCamera : Unsupported major.minor version 52.0

Which Java version should I use? with eclipse I can choose from 1.3 to 1.7. Or what could be the issue?

**Comment by Hopding** [comment]
Are you using the [prebuilt JAR](https://github.com/Hopding/JRPiCam/releases/tag/v1.1.1)? I believe it is built for `1.8`. Can you try using that version, and see if it resolves the error?
